apiVersion: v1
kind: Namespace
metadata:
  name: product-service-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-service-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-service-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
